if(NOT DataFormatsHLTReco_FOUND)
  set(DataFormatsHLTReco_FOUND TRUE)
  mark_as_advanced(DataFormatsHLTReco_FOUND)
cms_find_package(DataFormatsCandidate)
cms_find_package(DataFormatsCLHEP)
cms_find_package(DataFormatsCommon)
cms_find_package(FWCoreUtilities)
cms_find_package(boost)
list(APPEND LIBS DataFormatsHLTReco)
endif()
