if(NOT ROOFIT_FOUND)
  mark_as_advanced(ROOFIT_FOUND)
  set(ROOFIT_FOUND TRUE)
  cms_find_package(roofitcore)
  cms_find_package(rootcore)
  cms_find_package(rootmath)
  cms_find_package(roothistmatrix)
  list(APPEND LIBS RooFit)
endif()
