if(NOT DAVIX_FOUND)
	mark_as_advanced(DAVIX_FOUND)
	set(DAVIX_FOUND TRUE)
	cms_find_package(boost_system)
	cms_find_package(libxml2)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include/davix)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS davix)
endif()
