if(NOT FireworksVertices_FOUND)
  set(FireworksVertices_FOUND TRUE)
  mark_as_advanced(FireworksVertices_FOUND)
cms_find_package(FireworksCore)
cms_find_package(DataFormatsVertexReco)
cms_find_package(rootcore)
cms_find_package(opengl)
cms_find_package(Eve)
cms_find_package(Geom)
cms_find_package(Physics)
cms_find_package(RGL)
cms_find_package(Core)
list(APPEND LIBS FireworksVertices)
endif()
