if(NOT SimDataFormatsDigiSimLinks_FOUND)
  set(SimDataFormatsDigiSimLinks_FOUND TRUE)
  mark_as_advanced(SimDataFormatsDigiSimLinks_FOUND)
cms_find_package(DataFormatsMuonDetId)
cms_find_package(SimDataFormatsEncodedEventId)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS SimDataFormatsDigiSimLinks)
endif()
