if(NOT SimDataFormatsRPCDigiSimLink_FOUND)
  set(SimDataFormatsRPCDigiSimLink_FOUND TRUE)
  mark_as_advanced(SimDataFormatsRPCDigiSimLink_FOUND)
cms_find_package(SimDataFormatsEncodedEventId)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS SimDataFormatsRPCDigiSimLink)
endif()
