if(NOT DataFormatsBTauReco_FOUND)
  set(DataFormatsBTauReco_FOUND TRUE)
  mark_as_advanced(DataFormatsBTauReco_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(DataFormatsVertexReco)
cms_find_package(DataFormatsTrackReco)
cms_find_package(DataFormatsParticleFlowCandidate)
cms_find_package(DataFormatsMath)
cms_find_package(DataFormatsJetReco)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
cms_find_package(clhep)
cms_find_package(rootmath)
list(APPEND LIBS DataFormatsBTauReco)
endif()
