if(NOT LLVM_CXXCOMPILER_FOUND)
  mark_as_advanced(LLVM_CXXCOMPILER_FOUND)
  set(LLVM_CXXCOMPILER_FOUND TRUE)
  cms_find_package(gcc_cxxcompiler)
  list(APPEND PROJECT_CXXFLAGS  -Wno-c99-extensions)
  list(APPEND PROJECT_CXXFLAGS  -Wno-c++11-narrowing)
  list(APPEND PROJECT_CXXFLAGS  -D__STRICT_ANSI__)
  list(APPEND PROJECT_CXXFLAGS  -Wno-unused-private-field)
  list(APPEND PROJECT_CXXFLAGS  -Wno-unknown-pragmas)
  list(APPEND PROJECT_CXXFLAGS  -Wno-unused-command-line-argument)
  list(APPEND PROJECT_CXXFLAGS  -Wno-unknown-warning-option)
  list(APPEND PROJECT_CXXFLAGS  -ftemplate-depth=512)
  list(APPEND PROJECT_CXXFLAGS  -Wno-error=potentially-evaluated-expression)
  list(APPEND PROJECT_CXXFLAGS  -fsized-deallocation)
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Wno-non-template-friend )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Werror=format-contains-nul )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Werror=maybe-uninitialized )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Werror=unused-but-set-variable )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Werror=return-local-addr )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -fipa-pta )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -frounding-math )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -mrecip )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -Wno-psabi )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -fno-crossjumping )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -fno-aggressive-loop-optimizations )
  list(REMOVE_ITEM  PROJECT_CXXFLAGS -mlong-double-64 )
endif()
