if(NOT OPENSSL_FOUND)
  mark_as_advanced(OPENSSL_FOUND)
  set(OPENSSL_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS ssl)
  list(APPEND LIBS crypto)
endif()
