if(NOT OPENGL_FOUND)
	mark_as_advanced(OPENGL_FOUND)
	set(OPENGL_FOUND TRUE)
	list(APPEND LIBS GL)
	list(APPEND LIBS GLU)
        if( NOT APPLE)
		cms_find_package(x11)
        	list(APPEND LIBS Xfixes)
        	list(APPEND LIBS xcb-xfixes)
	endif()
endif()
