if(NOT DataFormatsHcalRecHit_FOUND)
  set(DataFormatsHcalRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsHcalRecHit_FOUND)
cms_find_package(DataFormatsHcalDigi)
cms_find_package(DataFormatsHcalDetId)
cms_find_package(DataFormatsCommon)
cms_find_package(DataFormatsCaloRecHit)
list(APPEND LIBS DataFormatsHcalRecHit)
endif()
