if(NOT ROOTINTERACTIVE_FOUND)
  mark_as_advanced(ROOTINTERACTIVE_FOUND)
  set(ROOTINTERACTIVE_FOUND TRUE)
  cms_find_package(libjpeg_turbo)
  cms_find_package(libpng)
  cms_find_package(rootgpad)
  cms_find_package(rootrint)
  list(APPEND LIBS Gui)
endif()
