if(NOT BOOST_FILESYSTEM_FOUND)
  mark_as_advanced(BOOST_FILESYSTEM_FOUND)
  set(BOOST_FILESYSTEM_FOUND TRUE)
  cms_find_package(boost_system)
  cms_find_package(boost)
  list(APPEND LIBS boost_filesystem)
endif()
