if(NOT PCRE_FOUND)
	mark_as_advanced(PCRE_FOUND)
	set(PCRE_FOUND TRUE)
	cms_find_package(root_cxxdefaults)
	cms_find_package(zlib)
	cms_find_package(bz2lib)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS pcre)
endif()
