if(NOT FWCorePythonParameterSet_FOUND)
  set(FWCorePythonParameterSet_FOUND TRUE)
  mark_as_advanced(FWCorePythonParameterSet_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreParameterSet)
cms_find_package(DataFormatsProvenance)
cms_find_package(boost)
cms_find_package(boost_python)
list(APPEND LIBS FWCorePythonParameterSet)
endif()
