if(NOT DataFormatsTrackingRecHit_FOUND)
  set(DataFormatsTrackingRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsTrackingRecHit_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(GeometryCommonDetUnit)
cms_find_package(DataFormatsGeometrySurface)
cms_find_package(DataFormatsCLHEP)
cms_find_package(DataFormatsCommon)
cms_find_package(clhep)
list(APPEND LIBS DataFormatsTrackingRecHit)
endif()
