if(NOT ROOFITCORE_FOUND)
  mark_as_advanced(ROOFITCORE_FOUND)
  set(ROOFITCORE_FOUND TRUE)
  cms_find_package(rootcore)
  cms_find_package(roothistmatrix)
  cms_find_package(rootgpad)
  cms_find_package(rootminuit)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS /build/cmsdev/slc7_amd64_gcc820/lcg/root/6.18.04-nmpfii/include)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS RooFitCore)
endif()
