if(NOT LIBTIFF_FOUND)
	mark_as_advanced(LIBTIFF_FOUND)
	set(LIBTIFF_FOUND TRUE)
	cms_find_package(root_cxxdefaults)
	cms_find_package(libjpeg_turbo)
	cms_find_package(zlib)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS tiff)
endif()
