if(NOT FireworksGenParticlePlugins_FOUND)
  set(FireworksGenParticlePlugins_FOUND TRUE)
  mark_as_advanced(FireworksGenParticlePlugins_FOUND)
cms_find_package(FireworksCore)
cms_find_package(FireworksCandidates)
cms_find_package(DataFormatsHepMCCandidate)
cms_find_package(rootcore)
cms_find_package(EG)
cms_find_package(Eve)
list(APPEND LIBS FireworksGenParticlePlugins)
endif()
