if(NOT BOOST_HEADER_FOUND)
  mark_as_advanced(BOOST_HEADER_FOUND)
  set(BOOST_HEADER_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS /build/cmsdev/slc7_amd64_gcc820/external/boost/1.67.0-pafccj/include)
endif()
