if(NOT DataFormatsGEMRecHit_FOUND)
  set(DataFormatsGEMRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsGEMRecHit_FOUND)
cms_find_package(DataFormatsCSCRecHit)
cms_find_package(DataFormatsGeometryVector)
cms_find_package(DataFormatsTrackingRecHit)
cms_find_package(DataFormatsMuonDetId)
cms_find_package(DataFormatsCommon)
cms_find_package(rootrflx)
list(APPEND LIBS DataFormatsGEMRecHit)
endif()
