if(NOT CommonToolsStatistics_FOUND)
  set(CommonToolsStatistics_FOUND TRUE)
  mark_as_advanced(CommonToolsStatistics_FOUND)
cms_find_package(FWCoreMessageLogger)
cms_find_package(DataFormatsCLHEP)
cms_find_package(clhep)
cms_find_package(boost)
list(APPEND LIBS CommonToolsStatistics)
endif()
