if(NOT PhysicsToolsUtilities_FOUND)
  set(PhysicsToolsUtilities_FOUND TRUE)
  mark_as_advanced(PhysicsToolsUtilities_FOUND)
cms_find_package(SimDataFormatsPileupSummaryInfo)
cms_find_package(FWCoreCommon)
cms_find_package(FWCoreUtilities)
cms_find_package(DataFormatsProvenance)
cms_find_package(DataFormatsCommon)
cms_find_package(roofit)
cms_find_package(rootcore)
cms_find_package(root)
cms_find_package(boost)
list(APPEND LIBS PhysicsToolsUtilities)
endif()
