if(NOT DataFormatsTrackCandidate_FOUND)
  set(DataFormatsTrackCandidate_FOUND TRUE)
  mark_as_advanced(DataFormatsTrackCandidate_FOUND)
cms_find_package(DataFormatsTrajectorySeed)
cms_find_package(DataFormatsTrackingRecHit)
cms_find_package(DataFormatsCLHEP)
cms_find_package(DataFormatsCommon)
cms_find_package(clhepheader)
list(APPEND LIBS DataFormatsTrackCandidate)
endif()
