if(NOT SimDataFormatsGeneratorProducts_FOUND)
  set(SimDataFormatsGeneratorProducts_FOUND TRUE)
  mark_as_advanced(SimDataFormatsGeneratorProducts_FOUND)
cms_find_package(DataFormatsCommon)
cms_find_package(FWCoreMessageLogger)
cms_find_package(FWCoreUtilities)
cms_find_package(hepmc)
cms_find_package(xz)
cms_find_package(roothistmatrix)
list(APPEND LIBS SimDataFormatsGeneratorProducts)
endif()
