if(NOT FWCoreUtilities_FOUND)
  set(FWCoreUtilities_FOUND TRUE)
  mark_as_advanced(FWCoreUtilities_FOUND)
cms_find_package(boost)
cms_find_package(boost_filesystem)
cms_find_package(boost_regex)
cms_find_package(rootcore)
cms_find_package(libuuid)
cms_find_package(tbb)
cms_find_package(md5)
list(APPEND LIBS FWCoreUtilities)
endif()
