if(NOT DataFormatsEcalRecHit_FOUND)
  set(DataFormatsEcalRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsEcalRecHit_FOUND)
cms_find_package(DataFormatsEcalDetId)
cms_find_package(DataFormatsCommon)
cms_find_package(DataFormatsCaloRecHit)
list(APPEND LIBS DataFormatsEcalRecHit)
endif()
