if(NOT CondFormatsExternal_FOUND)
  set(CondFormatsExternal_FOUND TRUE)
  mark_as_advanced(CondFormatsExternal_FOUND)
cms_find_package(DataFormatsProvenance)
cms_find_package(DataFormatsL1GlobalTrigger)
cms_find_package(DataFormatsEcalDetId)
cms_find_package(DataFormatsDetId)
cms_find_package(boost)
cms_find_package(boost_serialization)
cms_find_package(clhep)
cms_find_package(rootmath)
list(APPEND LIBS CondFormatsExternal)
endif()
