if(NOT BOOST_PROGRAM_OPTIONS_FOUND)
  mark_as_advanced(BOOST_PROGRAM_OPTIONS_FOUND)
  set(BOOST_PROGRAM_OPTIONS_FOUND TRUE)
  cms_find_package(boost)
  list(APPEND LIBS boost_program_options)
endif()
