if(NOT CLHEPHEADER_FOUND)
  mark_as_advanced(CLHEPHEADER_FOUND)
  set(CLHEPHEADER_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND PROJECT_CXXFLAGS  -Wno-error=unused-variable)
endif()
