if(NOT DataFormatsSiStripDigi_FOUND)
  set(DataFormatsSiStripDigi_FOUND TRUE)
  mark_as_advanced(DataFormatsSiStripDigi_FOUND)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS DataFormatsSiStripDigi)
endif()
