if(NOT FWCorePyDevParameterSet_FOUND)
  set(FWCorePyDevParameterSet_FOUND TRUE)
  mark_as_advanced(FWCorePyDevParameterSet_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreParameterSet)
cms_find_package(DataFormatsProvenance)
cms_find_package(py2_pybind11)
cms_find_package(python)
list(APPEND LIBS FWCorePyDevParameterSet)
endif()
