if(NOT FWCoreCommon_FOUND)
  set(FWCoreCommon_FOUND TRUE)
  mark_as_advanced(FWCoreCommon_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreParameterSet)
cms_find_package(DataFormatsProvenance)
list(APPEND LIBS FWCoreCommon)
endif()
