if(NOT GeometryCaloGeometry_FOUND)
  set(GeometryCaloGeometry_FOUND TRUE)
  mark_as_advanced(GeometryCaloGeometry_FOUND)
cms_find_package(DataFormatsGeometryVector)
cms_find_package(DataFormatsCaloTowers)
cms_find_package(DataFormatsHcalDetId)
cms_find_package(DataFormatsEcalDetId)
cms_find_package(clhep)
list(APPEND LIBS GeometryCaloGeometry)
endif()
