if(NOT FireworksVertices_FOUND)
  set(FireworksVertices_FOUND TRUE)
  mark_as_advanced(FireworksVertices_FOUND)
cms_find_package(rootcore)
cms_find_package(opengl)
cms_find_package(rooteve)
cms_find_package(rootgeom)
cms_find_package(rootphysics)
cms_find_package(rootrgl)
cms_find_package(rootcling)
list(APPEND LIBS FireworksVertices)
endif()
