if(NOT DataFormatsFWLite_FOUND)
  set(DataFormatsFWLite_FOUND TRUE)
  mark_as_advanced(DataFormatsFWLite_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreParameterSet)
cms_find_package(FWCoreFWLite)
cms_find_package(FWCoreCommon)
cms_find_package(DataFormatsProvenance)
cms_find_package(DataFormatsCommon)
cms_find_package(rootcore)
list(APPEND LIBS DataFormatsFWLite)
endif()
