if(NOT DataFormatsScalers_FOUND)
  set(DataFormatsScalers_FOUND TRUE)
  mark_as_advanced(DataFormatsScalers_FOUND)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS DataFormatsScalers)
endif()
