if(NOT DataFormatsBeamSpot_FOUND)
  set(DataFormatsBeamSpot_FOUND TRUE)
  mark_as_advanced(DataFormatsBeamSpot_FOUND)
cms_find_package(DataFormatsCLHEP)
cms_find_package(DataFormatsCommon)
cms_find_package(rootcore)
cms_find_package(rootsmatrix)
cms_find_package(clhep)
list(APPEND LIBS DataFormatsBeamSpot)
endif()
