if(NOT OPENGL_FOUND)
   mark_as_advanced(OPENGL_FOUND)
   set(OPENGL_FOUND TRUE)
   set(OpenGL_GL_PREFERENCE LEGACY)
   find_package(OpenGL)
   if(APPLE)
   list(APPEND LIBS ${OPENGL_gl_LIBRARY})
   list(APPEND LIBS ${OPENGL_glu_LIBRARY})
   else()
   list(APPEND LIBS ${OpenGL_gl_LIBRARY})
   list(APPEND LIBS ${OpenGL_glu_LIBRARY})
   endif()
   if( NOT APPLE )
       cms_find_package(x11)
   endif()
endif()
