if(NOT DataFormatsMETReco_FOUND)
  set(DataFormatsMETReco_FOUND TRUE)
  mark_as_advanced(DataFormatsMETReco_FOUND)
cms_find_package(DataFormatsHcalRecHit)
cms_find_package(DataFormatsEcalRecHit)
cms_find_package(DataFormatsJetReco)
cms_find_package(DataFormatsRecoCandidate)
cms_find_package(DataFormatsCommon)
cms_find_package(root)
list(APPEND LIBS DataFormatsMETReco)
endif()
