if(NOT DataFormatsCaloTowers_FOUND)
  set(DataFormatsCaloTowers_FOUND TRUE)
  mark_as_advanced(DataFormatsCaloTowers_FOUND)
cms_find_package(DataFormatsGeometryVector)
cms_find_package(DataFormatsHcalDetId)
cms_find_package(DataFormatsCandidate)
cms_find_package(FWCoreUtilities)
cms_find_package(DataFormatsMath)
cms_find_package(DataFormatsDetId)
cms_find_package(DataFormatsCommon)
list(APPEND LIBS DataFormatsCaloTowers)
endif()
