if(NOT CondFormatsRPCObjects_FOUND)
  set(CondFormatsRPCObjects_FOUND TRUE)
  mark_as_advanced(CondFormatsRPCObjects_FOUND)
cms_find_package(CondFormatsSerialization)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreMessageLogger)
cms_find_package(DataFormatsMuonDetId)
cms_find_package(DataFormatsDetId)
cms_find_package(boost)
cms_find_package(boost_serialization)
list(APPEND LIBS CondFormatsRPCObjects)
endif()
