if(NOT FireworksCandidates_FOUND)
  set(FireworksCandidates_FOUND TRUE)
  mark_as_advanced(FireworksCandidates_FOUND)
cms_find_package(FireworksCalo)
cms_find_package(FireworksCore)
cms_find_package(DataFormatsPatCandidates)
cms_find_package(DataFormatsCandidate)
cms_find_package(boost_system)
cms_find_package(rooteve)
list(APPEND LIBS FireworksCandidates)
endif()
