if(NOT FWCoreServiceRegistry_FOUND)
  set(FWCoreServiceRegistry_FOUND TRUE)
  mark_as_advanced(FWCoreServiceRegistry_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCorePluginManager)
cms_find_package(FWCoreParameterSet)
cms_find_package(DataFormatsProvenance)
list(APPEND LIBS FWCoreServiceRegistry)
endif()
