if(NOT DataFormatsTrajectoryState_FOUND)
  set(DataFormatsTrajectoryState_FOUND TRUE)
  mark_as_advanced(DataFormatsTrajectoryState_FOUND)
cms_find_package(DataFormatsGeometryVector)
cms_find_package(rootcore)
list(APPEND LIBS DataFormatsTrajectoryState)
endif()
