if(NOT FWCoreFWLite_FOUND)
  set(FWCoreFWLite_FOUND TRUE)
  mark_as_advanced(FWCoreFWLite_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCorePluginManager)
cms_find_package(DataFormatsProvenance)
cms_find_package(DataFormatsCommon)
cms_find_package(rootcore)
list(APPEND LIBS FWCoreFWLite)
endif()
