if(NOT DataFormatsEgammaReco_FOUND)
  set(DataFormatsEgammaReco_FOUND TRUE)
  mark_as_advanced(DataFormatsEgammaReco_FOUND)
cms_find_package(DataFormatsTrackReco)
cms_find_package(DataFormatsTrajectorySeed)
cms_find_package(DataFormatsTrackingRecHit)
cms_find_package(DataFormatsCaloRecHit)
cms_find_package(DataFormatsCommon)
cms_find_package(clhepheader)
list(APPEND LIBS DataFormatsEgammaReco)
endif()
