if(NOT DataFormatsHGCRecHit_FOUND)
  set(DataFormatsHGCRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsHGCRecHit_FOUND)
cms_find_package(DataFormatsHcalDetId)
cms_find_package(DataFormatsForwardDetId)
cms_find_package(DataFormatsCommon)
cms_find_package(DataFormatsCaloRecHit)
list(APPEND LIBS DataFormatsHGCRecHit)
endif()
