if(NOT PhysicsToolsFWLite_FOUND)
  set(PhysicsToolsFWLite_FOUND TRUE)
  mark_as_advanced(PhysicsToolsFWLite_FOUND)
cms_find_package(DataFormatsMuonReco)
cms_find_package(DataFormatsFWLite)
cms_find_package(CommonToolsUtils)
cms_find_package(boost)
cms_find_package(rootcore)
cms_find_package(roothistmatrix)
list(APPEND LIBS PhysicsToolsFWLite)
endif()
