if(NOT FireworksCalo_FOUND)
  set(FireworksCalo_FOUND TRUE)
  mark_as_advanced(FireworksCalo_FOUND)
cms_find_package(FireworksTracks)
cms_find_package(FireworksCore)
cms_find_package(DataFormatsJetReco)
cms_find_package(DataFormatsFWLite)
cms_find_package(DataFormatsEgammaReco)
cms_find_package(DataFormatsEcalRecHit)
cms_find_package(DataFormatsForwardDetId)
cms_find_package(DataFormatsEcalDetId)
cms_find_package(DataFormatsDetId)
cms_find_package(DataFormatsCaloTowers)
cms_find_package(DataFormatsCaloRecHit)
cms_find_package(boost_system)
cms_find_package(rootgpad)
cms_find_package(rootphysics)
cms_find_package(Eve)
cms_find_package(Geom)
list(APPEND LIBS FireworksCalo)
endif()
