if(NOT FWCoreFramework_FOUND)
  set(FWCoreFramework_FOUND TRUE)
  mark_as_advanced(FWCoreFramework_FOUND)
cms_find_package(FWCoreVersion)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreServiceRegistry)
cms_find_package(FWCorePluginManager)
cms_find_package(FWCoreParameterSet)
cms_find_package(FWCoreMessageLogger)
cms_find_package(FWCoreConcurrency)
cms_find_package(FWCoreCommon)
cms_find_package(DataFormatsProvenance)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
cms_find_package(rootcore)
list(APPEND LIBS FWCoreFramework)
endif()
