if(NOT X11_FOUND)
   mark_as_advanced(X11_FOUND)
   set(X11_FOUND TRUE)
   if( NOT APPLE )
       list(APPEND LIBS Xfixes)
       list(APPEND LIBS Xext)
       list(APPEND LIBS xcb)
       list(APPEND LIBS xcb-dri2)
       list(APPEND LIBS xcb-glx)
       list(APPEND LIBS xcb-xfixes)
       cms_find_package(sockets)
   endif()
endif()
