if(NOT CommonToolsUtils_FOUND)
  set(CommonToolsUtils_FOUND TRUE)
  mark_as_advanced(CommonToolsUtils_FOUND)
cms_find_package(FWCoreMessageLogger)
cms_find_package(FWCoreUtilities)
cms_find_package(FWCoreReflection)
cms_find_package(FWCoreParameterSet)
cms_find_package(DataFormatsMath)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
cms_find_package(roothistmatrix)
list(APPEND LIBS CommonToolsUtils)
endif()
