if(NOT DataFormatsMuonReco_FOUND)
  set(DataFormatsMuonReco_FOUND TRUE)
  mark_as_advanced(DataFormatsMuonReco_FOUND)
cms_find_package(DataFormatsVertexReco)
cms_find_package(DataFormatsGEMRecHit)
cms_find_package(DataFormatsCSCRecHit)
cms_find_package(DataFormatsDTRecHit)
cms_find_package(DataFormatsTrackReco)
cms_find_package(DataFormatsRecoCandidate)
cms_find_package(DataFormatsCommon)
cms_find_package(rootmath)
list(APPEND LIBS DataFormatsMuonReco)
endif()
