if(NOT DataFormatsSiStripCluster_FOUND)
  set(DataFormatsSiStripCluster_FOUND TRUE)
  mark_as_advanced(DataFormatsSiStripCluster_FOUND)
cms_find_package(DataFormatsTrajectoryState)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS DataFormatsSiStripCluster)
endif()
