if(NOT ROOTCLING_FOUND)
  mark_as_advanced(ROOTCLING_FOUND)
  set(ROOTCLING_FOUND TRUE)
  cms_find_package(root_interface)
  cms_find_package(sockets)
  cms_find_package(pcre)
  cms_find_package(zlib)
  cms_find_package(xz)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND LIBS Core)
endif()
