if(NOT SimDataFormatsCaloHit_FOUND)
  set(SimDataFormatsCaloHit_FOUND TRUE)
  mark_as_advanced(SimDataFormatsCaloHit_FOUND)
cms_find_package(SimDataFormatsEncodedEventId)
cms_find_package(DataFormatsMath)
cms_find_package(DataFormatsCommon)
cms_find_package(boost)
list(APPEND LIBS SimDataFormatsCaloHit)
endif()
