if(NOT LIBUUID_FOUND)
  mark_as_advanced(LIBUUID_FOUND)
  set(LIBUUID_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  cms_find_package(sockets)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS uuid)
endif()
