if(NOT GDBM_FOUND)
  mark_as_advanced(GDBM_FOUND)
  set(GDBM_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS gdbm)
endif()
