if(NOT DataFormatsCaloRecHit_FOUND)
  set(DataFormatsCaloRecHit_FOUND TRUE)
  mark_as_advanced(DataFormatsCaloRecHit_FOUND)
cms_find_package(DataFormatsDetId)
cms_find_package(DataFormatsCommon)
cms_find_package(rootmath)
list(APPEND LIBS DataFormatsCaloRecHit)
endif()
