if(NOT XROOTD_FOUND)
  mark_as_advanced(XROOTD_FOUND)
  set(XROOTD_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include/xrootd)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include/xrootd/private)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS XrdUtils)
  list(APPEND LIBS XrdClient)
endif()
