if(NOT FWCorePluginManager_FOUND)
  set(FWCorePluginManager_FOUND TRUE)
  mark_as_advanced(FWCorePluginManager_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(boost)
cms_find_package(tbb)
cms_find_package(rootcore)
cms_find_package(stdcxx_fs)
list(APPEND LIBS FWCorePluginManager)
endif()
