if(NOT ROOTDATAFRAME_FOUND)
  mark_as_advanced(ROOTDATAFRAME_FOUND)
  set(ROOTDATAFRAME_FOUND TRUE)
  cms_find_package(rootcore)
  cms_find_package(rootgraphics)
  cms_find_package(roothistmatrix)
  cms_find_package(rootrio)
  cms_find_package(rootvecops)
  list(APPEND LIBS ROOTDataFrame)
endif()
