if(NOT DataFormatsMath_FOUND)
  set(DataFormatsMath_FOUND TRUE)
  mark_as_advanced(DataFormatsMath_FOUND)
cms_find_package(DataFormatsCommon)
cms_find_package(rootmath)
list(APPEND LIBS DataFormatsMath)
endif()
