if(NOT TBB_FOUND)
  mark_as_advanced(TBB_FOUND)
  set(TBB_FOUND TRUE)
  cms_find_package(root_cxxdefaults)
  list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
  list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
  list(APPEND LIBS tbb)
  list(APPEND PROJECT_CPPDEFINES -DTBB_USE_GLIBCXX_VERSION=80301)
endif()
