if(NOT FastSimDataFormatsExternal_FOUND)
  set(FastSimDataFormatsExternal_FOUND TRUE)
  mark_as_advanced(FastSimDataFormatsExternal_FOUND)
cms_find_package(DataFormatsDetId)
cms_find_package(DataFormatsGeometrySurface)
cms_find_package(DataFormatsCommon)
list(APPEND LIBS FastSimDataFormatsExternal)
endif()
