if(NOT DataFormatsHcalDetId_FOUND)
  set(DataFormatsHcalDetId_FOUND TRUE)
  mark_as_advanced(DataFormatsHcalDetId_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(DataFormatsDetId)
cms_find_package(boost)
list(APPEND LIBS DataFormatsHcalDetId)
endif()
