if(NOT LIBUNGIF_FOUND)
	mark_as_advanced(LIBUNGIF_FOUND)
	set(LIBUNGIF_FOUND TRUE)
	cms_find_package(root_cxxdefaults)
	cms_find_package(zlib)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS ungif)
endif()
