if(NOT LIBJPEG_TURBO_FOUND)
	mark_as_advanced(LIBJPEG_TURBO_FOUND)
	set(LIBJPEG_TURBO_FOUND TRUE)
	cms_find_package(root_cxxdefaults)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS jpeg)
endif()
