if(NOT DataFormatsCandidate_FOUND)
  set(DataFormatsCandidate_FOUND TRUE)
  mark_as_advanced(DataFormatsCandidate_FOUND)
cms_find_package(FWCoreUtilities)
cms_find_package(DataFormatsMath)
cms_find_package(DataFormatsGeometryVector)
cms_find_package(DataFormatsCommon)
cms_find_package(rootmath)
list(APPEND LIBS DataFormatsCandidate)
endif()
