if(NOT SIGCPP_FOUND)
	mark_as_advanced(SIGCPP_FOUND)
	set(SIGCPP_FOUND TRUE)
	cms_find_package(root_cxxdefaults)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include/sigc++-2.0)
	list(APPEND INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/lib/sigc++-2.0/include)
	list(APPEND LIBRARY_DIRS ${CMAKE_INSTALL_PREFIX}/lib)
	list(APPEND LIBS sigc-2.0)
endif()
