if(NOT ROOSTATS_FOUND)
  mark_as_advanced(ROOSTATS_FOUND)
  set(ROOSTATS_FOUND TRUE)
  cms_find_package(roofitcore)
  cms_find_package(roofit)
  cms_find_package(rootcore)
  cms_find_package(roothistmatrix)
  cms_find_package(rootgpad)
  list(APPEND LIBS RooStats)
endif()
