if(NOT ROOTRGL_FOUND)
  mark_as_advanced(ROOTRGL_FOUND)
  set(ROOTRGL_FOUND TRUE)
  cms_find_package(rootglew)
  cms_find_package(rootgui)
  cms_find_package(rootinteractive)
  cms_find_package(rootgraphics)
  list(APPEND LIBS RGL)
endif()
