if(NOT FireworksVerticesPlugins_FOUND)
  set(FireworksVerticesPlugins_FOUND TRUE)
  mark_as_advanced(FireworksVerticesPlugins_FOUND)
cms_find_package(FireworksCandidates)
cms_find_package(FireworksVertices)
cms_find_package(FireworksCore)
cms_find_package(DataFormatsVertexReco)
cms_find_package(DataFormatsBTauReco)
cms_find_package(roothistmatrix)
cms_find_package(Eve)
cms_find_package(Geom)
cms_find_package(Core)
list(APPEND LIBS FireworksVerticesPlugins)
endif()
